title: &title 'Intelligent and Autonomous Systems Lab'
baseurl: 'https://iasl.ics.uci.edu/'
languagecode: 'en-US'
pluralizelisttitles: false

markup:
  goldmark:
    renderer:
      unsafe: true  # For embedded HTML in content/_index.md.

enableRobotsTXT: true
outputs:
  home: [HTML]
  section: [HTML]
  taxonomy: [HTML]
  term: [HTML]
disableKinds:
- taxonomy
- taxonomyTerm

params:
  author: *title
  description: >-
    Latest updates, results, and publications
    by the Intelligent and Autonomous Systems Lab
    at University of California, Irvine
  contact:
    name: 'Marco Levorato'
    email: 'levorato+www@uci.edu'
  copyright:
    title: 'IASL'
    url: 'https://github.com/uci-iasl/website'
  datedayfmt: 'Jan 2, 2006'
  datedaytimefmt: 'Jan 2, 2006, 15:04 MST'

  bibliography:
    abbrevmonths: true
    fullnames: false
    etalcutoff: 5
    etalkeep: 2
    citefirstnames: false
    citetitlecutoff: 30

    nameparts:
    - key: 'first'
      priority: 3
    - key: 'middle'
      priority: 4
    - key: 'last'
      priority: 1
    - key: 'lineage'
      priority: 2

    urltemplates:
      doi: 'https://doi.org/%s'
      eprint:
        arxiv: 'https://arxiv.org/abs/%s'
        hdl: 'https://hdl.handle.net/%s'
        jstor: 'https://www.jstor.org/stable/%s'
        pubmed: 'https://www.ncbi.nlm.nih.gov/pubmed/%s'

  people:
    roles:
    - id: 'faculty'
      plural: 'Faculty'
    - id: 'postdoc'
      plural: 'Postdocs'
    - id: 'student-phd'
      plural: 'Ph.D. Students'
    - id: 'student-masters'
      plural: 'Master’s Students'
    - id: 'alumnus-phd'
      plural: 'Ph.D. Alumni'
    - id: 'alumnus-masters'
      plural: 'Master’s Alumni'
    - id: 'visitor'
      plural: 'Visitors'

menu:
  main:
  - name: 'People'
    url: '/people/'
    weight: 1
  - name: 'Projects'
    url: '/projects/'
    weight: 2
  - name: 'Publications'
    url: '/publications/'
    weight: 3
