title: &title 'Intelligent and Autonomous Systems Lab'
baseurl: 'https://iasl.ics.uci.edu/'
languagecode: 'en-US'
pluralizelisttitles: false

markup:
  goldmark:
    renderer:
      unsafe: true  # For embedded HTML in content/_index.md.

enableRobotsTXT: true
outputs:
  home: [HTML]
  section: [HTML]
  taxonomy: [HTML]
  term: [HTML]
disableKinds:
- taxonomy
- taxonomyTerm

params:
  author: *title
  description: >-
    Latest updates, results, and publications
    by the Intelligent and Autonomous Systems Lab
    at University of California, Irvine
  copyright:
    startyear: 2014
    label: 'IASL'
    url: 'https://github.com/uci-iasl/website'
  contacts:
  - label: 'Marco Levorato'
    url: 'mailto:Marco Levorato <levorato+www@uci.edu>'
  dateformat: 'Jan 2, 2006'
  datetimeformat: 'Jan 2, 2006, 15:04 MST'

  bibliography:
    format:
      nameparts:
      - key: 'first'
        priority: 3
      - key: 'middle'
        priority: 4
      - key: 'last'
        priority: 1
      - key: 'lineage'
        priority: 2
      keywordseparators: [';', ',']

    display:
      showfullnames: false
      etalupwardsof: 6
      etalretainfirst: 2
      abbreviatemonths: true
      citefirstnames: false
      citetitlecutoff: 30

    attachments:
      manuscript:
        label: 'Manuscript'
        paths:
        - 'pub/%s.pdf'
        weight: 1
      supplement:
        label: 'Supplement'
        paths:
        - 'pub/%s-supplement.pdf'
        weight: 2
      poster:
        label: 'Poster'
        paths:
        - 'pub/%s-poster.pdf'
        weight: 3
      slidedeck:
        label: "Slide\u00A0Deck"
        paths:
        - 'pub/%s-slidedeck.pdf'
        - 'pub/%s-slidedeck.pptx'
        - 'pub/%s-slidedeck.ppt'
        - 'pub/%s-slidedeck.key'
        - 'pub/%s-slidedeck.odp'
        weight: 4

    urltemplates:
      doi: 'https://doi.org/%s'
      eprint:
        arxiv: 'https://arxiv.org/abs/%s'
        hdl: 'https://hdl.handle.net/%s'
        jstor: 'https://www.jstor.org/stable/%s'
        pubmed: 'https://www.ncbi.nlm.nih.gov/pubmed/%s'

  people:
    roles:
      faculty:
        title: 'Faculty'
        sortby: [↑yearjoined, ↑name]
        weight: 1
      postdoc:
        title: 'Postdocs'
        sortby: [↑yearjoined, ↑name]
        weight: 2
      student-phd:
        title: 'Ph.D. Students'
        sortby: [↑yearjoined, ↑name]
        academicyearhint: true
        weight: 3
      student-masters:
        title: 'Master’s Students'
        sortby: [↑yearjoined, ↑name]
        academicyearhint: true
        weight: 4
      alumnus-phd:
        title: 'Ph.D. Alumni'
        sortby: [↓yeargraduated, ↑yearjoined, ↑name]
        featurewebsite: true
        weight: 5
      alumnus-masters:
        title: 'Master’s Alumni'
        sortby: [↓yeargraduated, ↑yearjoined, ↑name]
        featurewebsite: true
        weight: 6
      visitor:
        title: 'Visitors'
        sortby: [↑yearjoined, ↑name]
        featurewebsite: true
        weight: 7

    # The earliest date by which the Fall quarter is guaranteed to
    # have started. Used for academic-year hints in year ranges.
    academicyeartransitdate: '%d-10-01T00:00:00-0700'

menu:
  main:
  - name: 'People'
    url: '/people/'
    weight: 1
  - name: 'Projects'
    url: '/projects/'
    weight: 2
  - name: 'Publications'
    url: '/publications/'
    weight: 3
