#!/usr/bin/env bash
#
#	mkbibdata [bib-file ...]
#
# Converts the BibTeX bibliography files given in the arguments
# into YAML data files in the data/bib directory. If no arguments
# are present, looks for *.bib files in the static/bib directory.
#
# Must be run from the root directory of the source tree.

argv0dir="$(dirname "$0")"

. "$argv0dir"/libusage.bash
usage='[bib-file ...]'

bibdir='static/bib'
yamldir='data/bib'
bibtex2yaml="$argv0dir/bibtex2yaml"

bibfiles=("$@")
if [[ $# -eq 0 ]]; then
	[[ -d $bibdir ]] || panic "$bibdir: directory does not exist"
	i=0
	while IFS= read -r -d $'\0' file; do
		bibfiles[i++]="$file"
	done < <(find "$bibdir" -type f -name '*.bib' -print0)
	[[ ${#bibfiles[@]} -gt 0 ]] || panic "$bibdir: directory has no *.bib files"
fi

[[ -d $yamldir ]] || panic "$yamldir: directory does not exist"
[[ -x $bibtex2yaml ]] || panic "$bibtex2yaml: not an executable file"

rc=0
logerr() { log "$@"; rc=1; }

for bib in "${bibfiles[@]}"; do
	[[ -r $bib ]] || { logerr "$bib: not a readable file"; continue; }
	yaml="$yamldir/$(basename "${bib%%.bib}").yaml"
	"$bibtex2yaml" --include-bibtex --reformat-source "$bib" >"$yaml" || {
		logerr "$bibtex2yaml: exit $?"
		logerr "$bib: conversion has failed"
	}
done

while IFS= read -r -d $'\0' yaml; do
	bib="$bibdir/$(basename "${yaml%%.yaml}").bib"
	[[ -f $bib ]] || logerr "$bib: missing source file for $yaml"
done < <(find "$yamldir" -type f -name '*.yaml' -print0)

exit "$rc"
