#!/bin/bash
#
#	mkbibdata [bib-file ...]
#
# Converts the BibTeX bibliography files given in the arguments into
# YAML configuration files in the data/bib/ directory. If no arguments
# are present, looks for *.bib files in the bib/ directory.
#
# Must be run from the root directory of the source tree.

bibdir='static/bib'
outdir='data/bib'
bibtex2yaml="$(dirname "$0")/bibtex2yaml"

[[ -d "$outdir" ]] || { echo "no $outdir directory in $PWD" >&2; exit 2; }

bibfiles=("$@")
if [[ $# -eq 0 ]]; then
	i=0
	while IFS= read -r -d $'\0' file; do
		bibfiles[i++]="$file"
	done < <(find "$bibdir" -type f -name '*.bib' -print0)
	[[ ${#bibfiles[@]} -gt 0 ]] || { echo "no *.bib files in $PWD/$bibdir" >&2; exit 2; }
fi

for bib in "${bibfiles[@]}"; do
	[[ -f "$bib" ]] || { echo "$bib: file does not exist" >&2; continue; }
	bibbase="$(basename "${bib%%.bib}")"
	"$bibtex2yaml" "$bib" >"$outdir/$bibbase.yaml"
done
