#!/bin/bash
#
#	mkbibdata [bib-file ...]
#
# Converts the BibTeX bibliography files given in the arguments into
# YAML configuration files in the data/bib/ directory. If no arguments
# are present, looks for *.bib files in the bib/ directory.
#
# Must be run from the root directory of the source tree.

bibdir='static/bib'
yamldir='data/bib'
bibtex2yaml="$(dirname "$0")/bibtex2yaml"

[[ -d "$yamldir" ]] || { echo "no $yamldir directory in $PWD" >&2; exit 2; }

bibfiles=("$@")
if [[ $# -eq 0 ]]; then
	i=0
	while IFS= read -r -d $'\0' file; do
		bibfiles[i++]="$file"
	done < <(find "$bibdir" -type f -name '*.bib' -print0)
	[[ ${#bibfiles[@]} -gt 0 ]] || { echo "no *.bib files in $PWD/$bibdir" >&2; exit 2; }
fi

for bib in "${bibfiles[@]}"; do
	[[ -f "$bib" ]] || { echo "$bib: file does not exist" >&2; continue; }
	yaml="$yamldir/$(basename "${bib%%.bib}").yaml"
	"$bibtex2yaml" --include-bibtex "$bib" >"$yaml"
done

while IFS= read -r -d $'\0' yaml; do
	bib="$bibdir/$(basename "${yaml%%.yaml}").bib"
	[[ -f "$bib" ]] || echo "no $bib counterpart for $yaml" >&2
done < <(find "$yamldir" -type f -name '*.yaml' -print0)
